### ISSUE TITLE
DataTransporter creates duplicates on inactive records.

### ISSUE THREAD

**Issue by nzhome** [bcolpaert/Colso.Xrm.DataTransporter#6]
StateCode is not available to pick from, all my records creates double ups.  because it brings across all Inactive ones too, but it sets them all to ACtive, all my Inactive ones turn into Active records making them look like like duplicates in the Target system.   yes I want the Inactive ones because there is history associated with them.   but how do I set the statecode correctly during DataTransporting?

**Comment by nzhome** [comment]
I see you added the setState code,  but the statecode/statuscode attributes are not available to Checkbox to true, in the list of attributes.   how do I go about making use of that feature?

**Comment by nzhome** [comment]
DataTransporter.cs  Line 403,  why are we skipping the most important field in CRM?  the statecode and statuscode?

// Skip "statecode", "statuscode" (should be updated via SetStateRequest)
                                if (!attribute.LogicalName.Equals("statecode")
                                && !attribute.LogicalName.Equals("statuscode"))

**Comment by nzhome** [comment]
It should only set the state request when the statecode = 1 (Inactive), because the default is already Active.

**Comment by bcolpaert** [comment]
Hi nzhome, 

I skip state and status fields because not all entities are set via setstaterequest (like for example close incident request) and the application should be able to handle all kind of entities.

I could copy the active statuscodes, but all non-active (inactive/completed/cancelled...) statuscodes will be skipped, so they will remain active on the target environment. This can be confusing if some statuscodes are transferred and some are not. 
This is why I decided to skip all states/status in the first place.

If you have a proper solution for this, I would be happy to implement this....

A temporary workaround could be to only transfer Active/Inactive records, via the filter functionality and manually update the states on the target...
